import { Geist, Geist_Mono } from "next/font/google";
import AOSInitializer from "@/app/components/AOSInitializer";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-primary">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary `}
      >
        <AOSInitializer/>
        {children}
      </body>
    </html>
  );
}
