import { Geist, Geist_Mono } from "next/font/google";
import { CiLinkedin } from "react-icons/ci";
import AOSInitializer from "@/app/components/AOSInitializer";
import { FaInstagram } from "react-icons/fa";
import Spotlight from "./components/Spotlight";

import { SiCredly } from "react-icons/si";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons:{
    icon:[
      {url:'/favicon.ico', type: 'image/x-icon'}
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-primary">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary `}
      >
        <AOSInitializer/>
        <Spotlight/>
        {children}
        <footer className="mt-4 footer sm:footer-horizontal bg-grey/10 text-neutral-content items-center px-6 pt-3">
        <div className="absolute lg:mb-[170px] lg:block hidden z-20">
        <img src="/images/character/peek.png" alt="Chibi 1" className="w-28 h-24"/>
        </div>
          <aside className="flex items-center text-white">
            <p>Copyright © {new Date().getFullYear()} - All right reserved</p>
          </aside>
          <nav className="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
            <a href="www.linkedin.com/in/sabrina ">
              <CiLinkedin className="text-white hover:text-blue/70 transition-all duration-300 text-3xl hover:-translate-y-2"/>
            </a>
            <a href="https://www.credly.com/users/sabrina-shafer">
              <SiCredly className="pb-1 text-white hover:text-blue/70 transition-all duration-300 text-5xl hover:-translate-y-2"/>
            </a>
            <a>
              <FaInstagram  className="text-white hover:text-blue/70 transition-all duration-300 text-3xl hover:-translate-y-2"/>
            </a>
          </nav>
        </footer>
      </body>
    </html>
  );
}
